image: node:latest

services:
  - mongo:latest
  - redis:latest

cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js

test_db:
  script:
   - npm install
   - node ./specs/start.js ./specs/db-postgres.spec.js
